User.create!([
  {email: "ben@test.com", password: "password", encrypted_password: "$2a$10$7nsAJvSWr6F5h31jJI.2NuAn3EZiaYcMNLFDMVBsedVpDWXnc8hRy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-09-16 15:18:37", last_sign_in_at: "2015-09-16 15:18:37", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: nil, last_name: nil, dob: nil, city: nil, country: nil, cohort: nil, personal_statement: nil, employment_status: nil, startup_status: nil},
  {email: "bob@test.com", password: "password", encrypted_password: "$2a$10$Oq2CvecZV6NJKDRsVFdd/ukRYk.CzP2ENhDqrtzqWwtF0Nk2X5JCO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-09-16 15:24:38", last_sign_in_at: "2015-09-16 15:22:37", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: nil, last_name: nil, dob: nil, city: nil, country: nil, cohort: nil, personal_statement: nil, employment_status: nil, startup_status: nil},
  {email: "joe@test.com", password: "password", encrypted_password: "$2a$10$fprS1RfGUV0vTL2Ncia.H.6.2r/Hsx0mcsHkUklITUgVKC57XwpG.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-09-18 10:43:36", last_sign_in_at: "2015-09-16 15:35:45", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: nil, last_name: nil, dob: nil, city: nil, country: nil, cohort: nil, personal_statement: nil, employment_status: nil, startup_status: nil},
  {email: "bill@test.com", password: "password", encrypted_password: "$2a$10$Dp2PVG43nAU7zCiUyMqY1eNkxM2oZC3G7Hv2erV5U7sGqaW7P/wYi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-09-18 10:44:14", last_sign_in_at: "2015-09-17 18:10:41", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: nil, last_name: nil, dob: nil, city: nil, country: nil, cohort: nil, personal_statement: nil, employment_status: nil, startup_status: nil}
])
Employer.create!([
  {company_name: "Google", start_date: "2015-09-09", end_date: "2015-09-19", city: "NYC", country: "USA", user_id: 1, role: "CEO"},
  {company_name: "Apple", start_date: "2015-09-02", end_date: "2015-09-26", city: "Schoenberg/Holstein", country: "Germany", user_id: 2, role: "Database Admin"},
  {company_name: "Uber", start_date: "2015-09-10", end_date: "2015-09-18", city: "Paris", country: "France", user_id: 3, role: "VP"},
  {company_name: "FlipKart", start_date: "2015-09-02", end_date: "2015-09-19", city: "Anywhere", country: "Everywhere", user_id: 4, role: "Founder & CEO"}
])
Profile.create!([
  {user_id: 2, first_name: "Bob", last_name: "Jones", dob: "2015-09-15", city: "Cardiff", country: "Wales", cohort: "July 2015", personal_statement: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n", employment_status: "0", startup_status: "0", avatar_file_name: "mockup.png", avatar_content_type: "image/png", avatar_file_size: 58867, avatar_updated_at: "2015-09-16 15:21:48"},
  {user_id: 1, first_name: "Ben", last_name: "Smith", dob: "2015-09-18", city: "London", country: "UK", cohort: "July 2015", personal_statement: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n", employment_status: "0", startup_status: "0", avatar_file_name: "mockup.png", avatar_content_type: "image/png", avatar_file_size: 58867, avatar_updated_at: "2015-09-18 10:43:19"},
  {user_id: 3, first_name: "Joe", last_name: "Bloggs", dob: "2015-09-10", city: "Paris", country: "France", cohort: "July 2015", personal_statement: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n", employment_status: "0", startup_status: "0", avatar_file_name: "mockup.png", avatar_content_type: "image/png", avatar_file_size: 58867, avatar_updated_at: "2015-09-18 10:43:59"},
  {user_id: 4, first_name: "Bill", last_name: "Baggins", dob: nil, city: "London", country: "UK", cohort: "July 2015 ", personal_statement: "Lorem ipsum dolor sit amet, fugit volumus repudiare ad vim, ex wisi delectus theophrastus mea. Novum choro dolorem mei at, eu mea laoreet veritus quaerendum, ad inani laudem graeci his. Magna persecuti voluptaria cu mei, ne latine vivendum posidonium est. At cum amet unum ornatus. Cu eam habemus eligendi, eam unum propriae no. Numquam efficiendi an pri, mel at rationibus liberavisse. Qui at suscipit copiosae delicata, ne sit choro option euripidis, te sea odio partem vocent.\r\n\r\nUtroque minimum euripidis vix cu, dictas integre volutpat te eos, audire bonorum suscipiantur ea eam. Eam eu assueverit philosophia. Voluptua probatus cu pri, maiorum insolens contentiones sed id, eirmod cetero splendide an sed. Te est homero volumus, mea patrioque vulputate accommodare te. Ea pro nobis adipiscing, vim electram cotidieque eu.\r\n\r\nAliquid phaedrum at eam, no pro erat lorem ludus. Eum admodum appellantur ex. Ludus fierent cum no, mei ei maluisset assentior eloquentiam. Has novum errem munere an, eu nec deserunt iracundia theophrastus, id ipsum iuvaret sententiae eos. Persius molestie ei his, mel mazim intellegebat et. Et dicat tincidunt cum.\r\n", employment_status: "0", startup_status: "0", avatar_file_name: "mockup.png", avatar_content_type: "image/png", avatar_file_size: 58867, avatar_updated_at: "2015-09-18 10:44:27"}
])
